#!/bin/sh
set -eu

REPO="https://github.com/Jackson4Rocks/miniland"
RAW_BASE="https://raw.githubusercontent.com/Jackson4Rocks/miniland/main"
BIN_DIR="$HOME/.local/bin"
HYPR_DIR="$HOME/.config/hypr"
HYPR_CONF="$HYPR_DIR/hyprland.conf"
MINILAND_CONF="$HYPR_DIR/miniland.conf"
INSTALL_BIN="$BIN_DIR/miniland"

say() {
    printf '%s %s\n' '==>' "$*"
}

warn() {
    printf '%s %s\n' 'warning:' "$*" >&2
}

die() {
    printf '%s %s\n' 'error:' "$*" >&2
    exit 1
}

say "Welcome to Miniland."
printf '%s\n' "This guided installer installs Miniland for your user account."
printf '%s\n\n' "No root access is required."

command -v jq >/dev/null 2>&1 || die "jq is required. Install jq and run this installer again."

normalize_token() {
    token="$1"
    token="$(printf '%s' "$token" | tr '[:lower:]' '[:upper:]')"

    case "$token" in
        CONTROL) printf '%s' 'CTRL' ;;
        CTRL) printf '%s' 'CTRL' ;;
        META|WINDOWS|WIN|GUI|MOD4) printf '%s' 'SUPER' ;;
        ESC|ESCAPE) printf '%s' 'ESCAPE' ;;
        ENTER) printf '%s' 'RETURN' ;;
        SPACE) printf '%s' 'SPACE' ;;
        BACKSPACE) printf '%s' 'BACKSPACE' ;;
        TAB) printf '%s' 'TAB' ;;
        DELETE|DEL) printf '%s' 'DELETE' ;;
        *) printf '%s' "$token" ;;
    esac
}

parse_bind() {
    raw="$1"
    oldifs="$IFS"
    IFS='+'
    set -- $raw
    IFS="$oldifs"

    count="$#"
    [ "$count" -gt 0 ] || return 1

    key=""
    mods=""
    i=1

    for part in "$@"; do
        part="$(printf '%s' "$part" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        [ -n "$part" ] || return 1
        token="$(normalize_token "$part")"

        if [ "$i" -eq "$count" ]; then
            key="$token"
        else
            case "$token" in
                SUPER|SHIFT|CTRL|ALT|ALTGR|CAPSLOCK|HYPER)
                    if [ -n "$mods" ]; then
                        mods="$mods $token"
                    else
                        mods="$token"
                    fi
                    ;;
                *) return 1 ;;
            esac
        fi

        i=$((i + 1))
    done

    [ -n "$key" ] || return 1
    printf '%s|%s' "$mods" "$key"
}

ask_bind() {
    prompt="$1"
    default="$2"

    while :; do
        printf '%s' "$prompt"
        IFS= read -r answer || answer=""

        if [ -z "$answer" ]; then
            printf '%s\n' "$default"
            return 0
        fi

        if parsed="$(parse_bind "$answer")"; then
            printf '%s\n' "$parsed"
            return 0
        fi

        warn "Invalid keybind. Try: SUPER + M or SUPER + SHIFT + M"
    done
}

binding_line() {
    parsed="$1"
    command="$2"

    mods="$(printf '%s' "$parsed" | cut -d'|' -f1)"
    key="$(printf '%s' "$parsed" | cut -d'|' -f2)"

    if [ -n "$mods" ]; then
        printf 'bind = %s, %s, exec, miniland %s\n' "$mods" "$key" "$command"
    else
        printf 'bind = , %s, exec, miniland %s\n' "$key" "$command"
    fi
}

download_miniland() {
    if [ -f "./miniland" ]; then
        cat ./miniland
    elif command -v curl >/dev/null 2>&1; then
        curl -fsSL "$RAW_BASE/miniland"
    elif command -v wget >/dev/null 2>&1; then
        wget -qO- "$RAW_BASE/miniland"
    else
        die "curl or wget is required to download Miniland."
    fi
}

printf '%s\n' "Keybind format: SUPER + M"
printf '%s\n' "Multiple modifiers work too: SUPER + SHIFT + M"
printf '%s\n\n' "Press Enter to accept the shown default."

minimize_bind="$(ask_bind 'Minimize focused window [SUPER + M]: ' 'SUPER|M')"
restore_bind="$(ask_bind 'Restore last minimized window [SUPER + SHIFT + M]: ' 'SUPER SHIFT|M')"
shelf_bind="$(ask_bind 'Show/hide Miniland shelf [SUPER + ALT + M]: ' 'SUPER ALT|M')"

mkdir -p "$BIN_DIR" "$HYPR_DIR"

say "Installing $INSTALL_BIN"
download_miniland > "$INSTALL_BIN"
chmod 755 "$INSTALL_BIN"

cat > "$MINILAND_CONF" <<EOF
# Miniland keybindings
# Generated by $REPO/install.sh

$(binding_line "$minimize_bind" "minimize")
$(binding_line "$restore_bind" "restore-last")
$(binding_line "$shelf_bind" "toggle-shelf")
EOF

if [ -f "$HYPR_CONF" ]; then
    if ! grep -Fq 'source = ~/.config/hypr/miniland.conf' "$HYPR_CONF"; then
        printf '\n# Miniland\nsource = ~/.config/hypr/miniland.conf\n' >> "$HYPR_CONF"
        say "Added Miniland to $HYPR_CONF"
    else
        say "Miniland is already sourced by Hyprland."
    fi
else
    cat > "$HYPR_CONF" <<EOF
# Hyprland configuration
source = ~/.config/hypr/miniland.conf
EOF
    say "Created $HYPR_CONF"
fi

printf '\n'
say "Miniland is installed."
printf '%s\n' "Executable: $INSTALL_BIN"
printf '%s\n' "Config:     $MINILAND_CONF"
printf '%s\n' "Bindings:"
binding_line "$minimize_bind" "minimize"
binding_line "$restore_bind" "restore-last"
binding_line "$shelf_bind" "toggle-shelf"

if command -v hyprctl >/dev/null 2>&1; then
    if hyprctl reload >/dev/null 2>&1; then
        say "Hyprland reloaded."
    else
        warn "Hyprland could not be reloaded automatically. Reload it manually."
    fi
fi

printf '\n%s\n' "Try: miniland list"
